#!/usr/bin/env bash
# WP1 — data inventory, generated from the live database.
# Prints a markdown table: table, rows, real vs synthetic, what it is, which WP consumes it.
# Usage: scripts/inventory.sh [connection-url]   (defaults to the local test env)
set -euo pipefail
URL="${1:-postgresql://postgres:${HAUTEL_DB_PASS:-hautel-dev-only}@localhost:54329/hautel}"
q() { psql "$URL" -At -c "$1"; }

# provenance: rows whose ids follow the synthetic-seed prefixes are synthetic; everything else counts as real
synth_orgs="$(q "select count(*) from organizations where id::text like 'a0000000-%'")"
real_orgs="$(q "select count(*) from organizations where id::text not like 'a0000000-%'")"
synth_docs="$(q "select count(*) from documents where source is null or source like 'synthetic%'")"
real_docs="$(q "select count(*) from documents where source is not null and source not like 'synthetic%'")"

row() { printf '| %s | %s | %s | %s | %s |\n' "$1" "$(q "select count(*) from $1")" "$2" "$3" "$4"; }

echo "| Table | Rows | Origin | What it holds | Consumed by |"
echo "|---|---|---|---|---|"
row organizations        "synthetic $synth_orgs / real $real_orgs" "Tenants: hotel groups or independents" "all WPs (tenancy)"
row properties           "synthetic" "One row per hotel; region, branding" "WP2 context, WP3 context"
row hotel_profiles       "synthetic" "Segment, audience, positioning, channels, strengths, weaknesses" "WP2 matching input, WP3 advice input"
row marketing_needs      "synthetic" "The need to be matched: title, brief, category, urgency, budget band" "WP2 matching input"
row consultants          "synthetic" "Freelancers/agencies: bio (unstructured), languages, region, day rate" "WP2 matching candidates"
row consultant_expertise "synthetic" "Skill + level + evidence per consultant" "WP2 matching candidates"
row documents            "synthetic $synth_docs / real $real_docs" "Unstructured briefs, bios, positioning docs (full text)" "WP2 retrieval, WP3 grounding"
row matches              "generated by WP2" "Ranked need→consultant proposals with score, rationale, model" "WP3 input, evidence"
row tasks                "generated by WP2" "Workflow triggered by a match (origin_kind='match'), with provenance" "evidence, later guest & ops"
row advice               "generated by WP3" "Strategic recommendation per hotel/need, grounded in cited sources" "evidence"
row evaluations          "generated by WP3" "Relevance / groundedness / consistency / human scores per match or advice" "VLAIO evidence"
row users                "empty" "Staff accounts (platform spine)" "later"
row memberships          "empty" "Role assignments org/property/department" "later"
row departments          "empty" "Housekeeping, F&B, ... (guest & ops extension)" "later"
row guests               "empty" "Guest profiles, minimized (guest & ops extension)" "later"
row stays                "empty" "Reservation windows linked to PMS (guest & ops extension)" "later"
row threads              "empty" "Conversation threads, channel-agnostic (guest & ops extension)" "later"
row messages             "empty" "Messages in threads (guest & ops extension)" "later"
row content              "empty" "Layered org→property content: brand rules, compendium (guest & ops / brand hub)" "later"
